#!/usr/bin/env python3

import sys
from util import *

def main(argv):
	# Get the file name and date from command line argument
	filename, date = parseCommandLine(argv)
	
	# Parse the csv file and format the data into a dictionary.
	# Maps date to another dictionary that maps cookies to counts.
	# Essentially keeps track of cookie occurences on specific dates.
	dic = parseCSV(filename)
	
	# Get the most active cookies from the dictionary
	mostActiveCookie(dic, date)
	
	return
	
	
if __name__ == "__main__":
	main(sys.argv)
