#!/usr/bin/env python3

import sys
from util import *

def main(argv):
	# get the file name and date from command line argument
	filename, date = parseCommandLine(argv)
	
	# parse the csv file and format the data into a dictionary
	dic = parseCSV(filename)
	
	# Get the most active cookies from the dictionary
	mostActiveCookie(dic, date)
	
	return
	
	
if __name__ == "__main__":
	main(sys.argv)